### ISSUE TITLE
Saas website check-in

### ISSUE THREAD

**Issue by jessicali673** [jessicali673/saas-website#2]
Hey Christina! 
Here is my issue for the saas- check in and my work-in-progress.

1. Question about my header navigation: I still see bullets on the nav but I tried indicating list-style-group none to my nav, nav ul, nav li and nav a. The bullets just won't go away! I used list-group-inline class in the html if this has something to do with it. 

2. On my features page, my image gets too large in height on my larger screens, when I set a height to the image in media query, the image looks squished. How do I make it look cropped instead?

Also here are screenshots of my quizzes:
![Screen Shot 2020-04-15 at 6 20 00 PM](https://user-images.githubusercontent.com/55094160/79678762-b482bd80-81cc-11ea-89bd-8c469fb99d22.png)
![Screen Shot 2020-04-15 at 8 23 49 PM](https://user-images.githubusercontent.com/55094160/79678764-b9477180-81cc-11ea-8ab1-22aef1855228.png)

@muxlowc

**Comment by muxlowc** [comment]
@jessicali673  1) im assuming you fixed the bullets? I dont see them on my end

2)  you can add in a few class to you main.css. You can add something called object-fit: cover, which basically stretches your image nicely, and then add a max-height of whatever height you want, and then because of object-fit, it should crop the image nicely.

  .home-img {
    opacity: 0.5;
    object-fit: cover;
    max-height: 500px;
  }

You will also probably have to change the content on this image to be top: 50% or something now instead. Hope this helps!
